### ISSUE TITLE
Emails sent from the contact form are not reply-able.

### ISSUE THREAD

**Issue by alexonea** [thetopor/thetopor.github.io#3]
It would be nice if we can directly reply to the emails sent via the contact form. This would imply that the email sender is somehow the email address of the user filling the form. In this way, replying to the email is possible directly and we don't need to edit a new email and copy the details. :)

**Comment by OriginalNexus** [comment]
You cannot send emails using someone else's email. What you can do is specify a `Reply-To` email so that the mail client you are using knows to redirect any replies to that email.

The `form-email.php` on the server needs to be changed. I'll do that right now.
